version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "provider"
    ports:
      - "3306:3306"

  application:
    image: application_provider:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    links:
      - mysql

  adminer:
    image: adminer
    ports:
      - "9090:8080"
